# https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
server:
  service:
    type: NodePort

configs:
  cmp:
    create: true
    plugins:
      helmfile:
        discover:
          filename: helmfile.yaml
        parameters:
          static:
            - name: name
              title: Helmfile App Label Name
              required: true
        generate:
          command:
            - bash
            - "-c"
            - |
                helmfile -e dev -l app="$PARAM_NAME" template --include-crds -q
repoServer:
  extraContainers:
    - name: helmfile-sidecar
      command:
        - /var/run/argocd/argocd-cmp-server
      image: ghcr.io/helmfile/helmfile:v1.2.2
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      env:
      - name: HELM_CACHE_HOME
        value: "/tmp/helm/cache"
      - name: HELM_CONFIG_HOME
        value: "/tmp/helm/config"
      - name: HELM_DATA_HOME
        value: "/tmp/helm/data"
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: helmfile.yaml
          name: argocd-cmp-cm
        - mountPath: /tmp
          name: helmfile-tmp
  volumes:
    - name: argocd-cmp-cm
      configMap:
        name: argocd-cmp-cm
    - name: helmfile-tmp
      emptyDir: {}

redisSecretInit:
  enabled: true

