# https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml
operator:
  metricsVulnIdEnabled: true
serviceMonitor:
  enabled: true
trivyOperator:
  scanJobTolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
nodeCollector:
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
