apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: multus-nad
spec:
  config: '{
          "cniVersion": "0.3.1",
          "plugins": [
            {
              "type": "macvlan",
              "master": "enp0s9",
              "mode": "bridge",
              "ipam": {
                "type": "whereabouts",
                "range": "10.0.0.0/27",
                "range_start": "10.0.0.15",
                "range_end": "10.0.0.19"
              }
            },
            {
              "capabilities": {
                "mac": true
              },
              "type": "tuning"
            }
          ]
        }'
