# https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml

# Speaker configuration
speaker:
  tolerateMaster: true
  resources:
    limits:
      cpu: 100m
      memory: 100Mi

# Controller configuration
controller:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi

# Note: You need to create IPAddressPool and L2Advertisement CRs after installation
# Example configuration (apply separately):
#
# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: default-pool
#   namespace: metallb-system
# spec:
#   addresses:
#   - 192.168.1.240-192.168.1.250  # Change to your available IP range
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: default
#   namespace: metallb-system
# spec:
#   ipAddressPools:
#   - default-pool
